name: Unit Test for PR Request

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - deploy-test
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.3

      - name: Install Pip
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Execute Tests
        run: |
          python -m pytest -s src/tests
